### ISSUE TITLE
Suggestion - %form% and %palette% for sprites

### ISSUE THREAD

**Issue by SirDoof** [EnvyWare/EnvyHunt#17]
Similar to the `%dex_number%` placeholder, one for form and palette would be great to show their sprite properly in the UI.
Currently, the pixelmon:pixelmon_sprite item fallsback to the poke ball if the form isn't specified for some pokemon such as sinistea or florges.

**Comment by danorris709** [comment]
Sorry I'm not really sure what you mean here. There's no random form generation spec, or random palette generation spec so where would it be pulling the form/palette data from?

**Comment by SirDoof** [comment]
I thought it would be similar to the `%dex_number%` placeholder that was recently added which doesn't have a random spec from what I can tell or that it would pull it from the species data.

**Comment by danorris709** [comment]
No so I think you've misunderstood how that placeholder works. That placeholder will only work if you've specified a species in one of the specs (i.e. `random`, `nidoran`, etc) so had you not put a species value in any of them then it would not have a value to pull from. So what that translates to for the form/palette is if there isn't a spec that specified it needs to be X palette or Y form then where would it know to pull the data from.

So I can add the placeholders for when you do specify a form & palette, but otherwise I recommend just setting it to the default form and default palette in the sprite's item NBT

**Comment by SirDoof** [comment]
Ah ok, I get it now. In that case, I don't think you need to add the placeholders since we can add form or palette names in the item name/lore.
